<script>
export default [
  {
    'title': 'cafe-bbs',
    'body': '今のところLaravelだけを使ったカフェの情報を載せるための掲示板です。デプロイはAWSのEC2に行なっています。DBはEC2の中に入れてある形です。ドメインをRoute53でつけて、常時SSL対応までしてあります。',
    'img': require('assets/images/cafebbs.png'),
    'img2': [require('assets/images/cafebbs1.png'), require('assets/images/cafebbs2.png'), require('assets/images/cafebbs3.png')],
    'img3': require('assets/images/cafebbs-res1.png'),
    'img4': require('assets/images/cafebbs-res2.png'),
    'tags': ['Laravel', 'AWS'],
  },
  {
    'title': 'RealTimeChat',
    'body': 'Websocketを使ったリアルタイム表示を作ってみたかったので、チャットを作りました。それとソーシャルログインもgithubのみ対応しています。デプロイはHerokuに行なっています。',
    'img': require('assets/images/chat4.png'),
    'img2': [require('assets/images/chat.png'), require('assets/images/chat2.png'), require('assets/images/chat.png')],
    'img3': require('assets/images/chat-res.png'),
    'img4': require('assets/images/chat-res2.png'),
    'url': 'https://laravuechat.herokuapp.com/',
    'github': 'https://github.com/roffet/realchat',
    'tags': ['Laravel', 'Vue.js', 'Pusher'],
  },
  {
    'title': 'hugo-blog',
    'body': 'ブログです。CMSなしで管理できるという点に惹かれて、静的ジェネレータのHugoを使って見ました。テーマはmainroadを使っています、色や配置はかなりカスタマイズしたものになってます。デプロイはnetlifyに行なっています。',
    'img': require('assets/images/hugologo.png'),
    'img2': [require('assets/images/hugo-caru.png'), require('assets/images/hugo-caru2.png'), require('assets/images/hugo-caru3.png')],
    'img3': require('assets/images/blog-res.png'),
    'img4': require('assets/images/blog-res2.png'),
    'url': 'https://roffet-blog.netlify.com/',
    'github': 'https://github.com/roffet/hugoblog',
    'tags': ['Hugo', 'netlify'],
  },
  {
    'title': 'portfolio',
    'body': 'このポートフォリオです。Nuxt.jsを土台にして、VuetifyというUIフレームワークで作りました。Vuetifyの機能をふんだんに使ったものになってます。デプロイは、GithubPagesにTravisCIを使って行なっています。',
    'img': require('assets/images/vuetify.png'),
    'img2': [require('assets/images/port-caru.png'), require('assets/images/port-caru2.png'), require('assets/images/port-caru3.png')],
    'img3': require('assets/images/port-res.png'),
    'img4': require('assets/images/port-res2.png'),
    'github': 'https://github.com/roffet/my-portfolio',
    'tags': ['Nuxt.js', 'Vuetify', 'TravisCI'],
  },
]
</script>
